### PR TITLE
migrate replicator-4.0alpha2 to run under Python 3

### PR DESCRIPTION
**Pull request by xedakini**
I've migrated your replicator caching server to run under Python 3 (instead of Python 2; I did not bother to maintain backward compatibility).  I also added a small amount of extra functionality to be compatible with the Gentoo distribution.

Given that your code has not been updated since 2008, I'm not sure how much you care, but I figured it'd at least be polite to let you know...

### CODE REVIEW

**Comment by gertjanvanzwieten** [comment]
Hi Xedakini, thanks! A lot of work I see. Indeed, as you guessed from lack of activity I have no time to maintain this repository anymore. So instead of me merging your commits here, I'd like to propose a transfer of ownership entirely. It's not a big change from the fork you already have except that this repository will automatically redirect to yours, and you inherit the issues and pull requests that I failed to follow up on. Let me know if you are interested.

**Comment by xedakini** [comment]
Well, it was a lot of commits, but most of them were small; I was just trying to document the steps I was taking so that it would be straightforward to follow along if one was so inclined.  The biggest bit of work was getting a handle on the testing, since I appear to have branched from some work-in-progress code rather than a release point.

I'm not sure about making a long-term commitment to being the maintainer (i'm actually trying to _decrease_ my time commitments), but I guess that it would be no worse mouldering under my github tree than yours, and I do have a few more thoughts about changes I'd like to add.  And sure, I'll take on looking at responding to various issues and pull requests before I relegate the code back to "benign neglect" status...  So if that works for you then sure, I'll catch the baton pass.

**Comment by gertjanvanzwieten** [comment]
Sounds good to me. So in order to transfer the repository I think you have to remove your fork first. I'll merge this PR now (without review) while the source branch still exists. Then if you can send me a heads up when things are clear on the receiving end I'll send a transfer invitation. Thanks for picking this up!

**Comment by xedakini** [comment]
Okay, fork has been deleted.

**Pull request merged**
